# Generated by Django 4.2.4 on 2023-09-03 02:44

import content.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=250)),
                ('preview', models.ImageField(upload_to='content/preview/')),
                ('description', models.TextField()),
                ('create_post', models.DateTimeField(auto_now_add=True)),
                ('update_post', models.DateTimeField(auto_now=True)),
                ('publish_post', models.DateTimeField(default=datetime.datetime(2023, 9, 3, 2, 44, 23, 298336, tzinfo=datetime.timezone.utc))),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='DF', max_length=2)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_content', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['-publish_post'],
            },
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=content.models.user_directory_path)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.content')),
            ],
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['-publish_post'], name='content_con_publish_980845_idx'),
        ),
    ]
